### ISSUE TITLE
openshift-install-wrapper --destroy uses original installation version instead of current version

### ISSUE THREAD

**Issue by palonsoro** [soukron/openshift-install-wrapper#16]
Opening this to have it around until I have time to propose a solution and/or allow somebody else to solve it.

Basically, if I do the following:
- Install cluster
- Upgrade cluster
- Destroy cluster

The cluster is destroyed with the openshift-install binary used at installation instead of the openshift-install binary matching the current cluster version.

Ideally, current cluster version should be guessed via `oc get clusterversion/version -o 'template={{.status.desired.version}}'` with admin kubeconfig and used.

**Comment by soukron** [comment]
Nice catch. Thanks for reporting it.

**Comment by soukron** [comment]
I understand the concerns, but for now we're staying as is. 

The destroy process will use the original version to avoid compatibility issues (if any) when reading the `metadata.json` file, but you can force a certain version by adding the `--version` parameter in the command line and it will be used.
